### ISSUE TITLE
Names with one double quote hang indefinitely

### ISSUE THREAD

**Issue by kalokagathia1** [Ghary/nameparts#6]
Try with `JOHN E. "POP GARSON SR.`

**Comment by Ghary** [comment]
Is the double quote supposed to be a mistake/typo or is it something actually used in names?
Also, what behavior or output are you expecting if it successfully parses?

**Comment by Ghary** [comment]
I made some assumptions and pushed 1.1.4 to fix this for you

**Comment by kalokagathia1** [comment]
@Ghary seems like it's working! Thanks so much for the quick response.
